WIDTH = 600
HEIGHT = 800

YELLOW = "#c9b458"
GREEN = "#6aaa64"
DARK_GRAY = "#787c7e"
LIGHT_GRAY = "#d3d6da"

LETTER_SIZE = 20

FONT = "assets/FreeSansBold.otf"

INDICATOR_SIZE_W = 40
INDICATOR_SIZE_H = 50

KEYBOARD_ALPHABET = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"]