WIDTH = 600
HEIGHT = 800

YELLOW = "#c9b458"
GREEN = "#6aaa64"
LIGHT_GRAY = "#787c7e"
DARK_GRAY = "#d3d6da"

LETTER_X_SPACING = 85
LETTER_Y_SPACING = 12
LETTER_SIZE = 15

FONT = "assets/FreeSansBold.otf"

INDICATOR_SIZE = 50

KEYBOARD_ALPHABET = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"]