WIDTH = 600
HEIGHT = 800

YELLOW = "#c9b458"
GREEN = "#6aaa64"
DARK_GRAY = "#787c7e"
LIGHT_GRAY = "#d3d6da"

KEYBOARD_LETTER_SIZE = 20
GUESS_LETTER_SIZE = 30

FONT = "assets/FreeSansBold.otf"

KEYBOARD_SIZE_W = 40
KEYBOARD_SIZE_H = 50

GUESS_SIZE_W = 70
GUESS_SIZE_H = 70

KEYBOARD_ALPHABET = ["QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"]